Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("Tudo Que Ela Gosta de Escutar");
Console.WriteLine("");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("Essa é uma história de amargar");
Console.WriteLine("Conheci uma garota meu irmão eu vou lhe falar");
Console.WriteLine("Tudo que ela quer o pai dela dá");
Console.WriteLine("Desde casa em Ubatuba até apê no Guarujá"); 
Console.WriteLine("");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("Fim de festa, olho pra ela, ela sorri pra mim");
Console.WriteLine("Me secou a noite inteira, ela só pode estar afim");
Console.WriteLine("Ela tem carro importado e telefone celular");
Console.WriteLine("Eu só tenho uma magrela e um apê no BNH");
Console.WriteLine("");
Console.WriteLine("Eu falo tudo que ela gosta de escutar");
Console.WriteLine("Deve ser por isso que ela vem me procurar");
Console.WriteLine("");
Console.WriteLine("Eu falo, eu falo tudo que ela gosta de escutar");
Console.WriteLine("Deve ser por isso que ela vem me procurar");
Console.WriteLine("");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("O pai dela riu de mim porque o meu carro é popular");
Console.WriteLine("E ainda me deu uma notícia de desanimar");
Console.WriteLine("Rapaz você não é bom pra minha filha não");
Console.WriteLine("Quem é teu pai? Quem é você? O que você faz?");
Console.WriteLine("Vou investigar você");
Console.WriteLine("");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("Fim de festa, olho pra ela, ela sorri pra mim");
Console.WriteLine("Me secou a noite inteira, ela só pode estar afimMe secou a noite inteira, ela só pode estar afim");
Console.WriteLine("Ela tem carro importado e telefone celular");
Console.WriteLine("Eu só tenho uma magrela e um apê no BNH");
Console.WriteLine("");
Console.WriteLine("Eu falo tudo que ela gosta de escutar");
Console.WriteLine("Deve ser por isso que ela vem me procurar");
Console.WriteLine("");
Console.WriteLine("Eu falo, eu falo tudo que ela gosta de escutar");
Console.WriteLine("Deve ser por isso que ela vem me procurar");
Console.WriteLine("");
Console.WriteLine("Eu falo, eu falo tudo que ela gosta de escutar");
Console.WriteLine("Deve ser por isso que ela vem me procurar");
Console.WriteLine("");
Console.WriteLine("Eu falo, eu falo tudo que ela gosta de escutar");
Console.WriteLine("Deve ser por isso que ela vem me procurar");
Console.ResetColor();
